name: CI/CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - docs/**
      - LICENSE.txt
      - README.md
  pull_request:
    branches:
      - master
    paths-ignore:
      - docs/**
      - LICENSE.txt
      - README.md

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Инициализация рабочего процесса
        uses: actions/checkout@v4
      - name: Подготовка JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - name: Сборка и тестирование проекта
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
          arguments: test
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Инициализация рабочего процесса
        uses: actions/checkout@v4
      - name: Подготовка JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - name: Сборка и публикация проекта
        uses: gradle/gradle-build-action@v2
        env:
          OSSRH_CREDENTIALS_USERNAME: ${{ secrets.OSSRH_CREDENTIALS_USERNAME }}
          OSSRH_CREDENTIALS_PASSWORD: ${{ secrets.OSSRH_CREDENTIALS_PASSWORD }}
          SINGING_KEY_ID: ${{ secrets.SINGING_KEY_ID }}
          SINGING_KEY_PASSWORD: ${{ secrets.SINGING_KEY_PASSWORD }}
          SINGING_KEY_SECRET: ${{ secrets.SINGING_KEY_SECRET }}
        with:
          gradle-version: 8.4
          arguments: publish
